### ISSUE TITLE
note sources

### ISSUE THREAD

**Issue by meodai** [words/tree-names#1]
Hey! Awesome repositories.

Would be super nice if we write down the sources per repo (And the fetched date). To make it easier to contribute if we find new ones. (On top of that we could automate pulling from this sources at some point)

**Comment by wooorm** [comment]
I think that’s a good idea, would be hard to trace back now for the things we already have. For the future, we could maybe add them as `yew // some source` in the text file, but I suggest tabling that until there’s interest to add more names!
